services:
  # mailserver:
  #   image: ghcr.io/docker-mailserver/docker-mailserver:latest
  #   container_name: mailserver
  #   # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
  #   hostname: mail.example.com
  #   ports:
  #     - "25:25"
  #     - "465:465"
  #     - "587:587"
  #     - "993:993"
  #   volumes:
  #     - ./docker-data/dms/mail-data/:/var/mail/
  #     - ./docker-data/dms/mail-state/:/var/mail-state/
  #     - ./docker-data/dms/mail-logs/:/var/log/mail/
  #     - ./docker-data/dms/config/:/tmp/docker-mailserver/
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - ENABLE_RSPAMD=1
  #     - ENABLE_CLAMAV=1
  #     - ENABLE_FAIL2BAN=1
  #   cap_add:
  #     - NET_ADMIN # For Fail2Ban to work
  #   restart: always

  mysql:
    image: mysql:latest
    container_name: drivable-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: drivable
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - driveable-net

  driveable-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: driveable-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://drivable-db:3306/drivable?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 20000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 300000
      SECURITY_JWT_SECRET: f66c30a11898b17133755179dd5c62a14a70ee4e10255bb4ee6fea5cea639d9ee2df5e04f2518f088c969ef9b99e898d195e6447efca52449f35b28df22226f4d7f4f271090e700dcc86c6e1ebd2e8b1405f21216997468...
      SECURITY_JWT_EXPIRATION_TIME: 3600000
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      # - mailserver
    networks:
      - driveable-net

volumes:
  mysql-data:

networks:
  driveable-net:
    driver: bridge
