spring.application.name=Driveable

spring.datasource.url=jdbc:mysql://localhost:3306/drivable?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=user
spring.datasource.password=password

spring.data.jdbc.dialect=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

security.jwt.secret="f66c30a11898b17133755179dd5c62a14a70ee4e10255bb4ee6fea5cea639d9ee2df5e04f2518f088c969ef9b99e898d195e6447efca52449f35b28df22226f4d7f4f271090e700dcc86c6e1ebd2e8b1405f2121699746854a789fd922292f9f7a8bba2c743e84d2a152529e3d418b563cc64868186263055e091e75e030a90412beb5c5f0ae8a648808b7219841a9ff47fe46d06cef291f133495fb565750c397cd8f874d5d609e7e188c2429e951af28e0c3ecbb38f6c85bd0ecebc13e555c24c2ad8c5f2c2ad790465bd9ed9263d1c65392942099f2427316b9196bd7c66f9c48c3c3ea882c79cf8e6d4f8402cb705949abe8e22187e3af091712948a8d65"
security.jwt.expiration-time=3600000

springdoc.swagger-ui.path=/swagger-ui.html


# --- Email Service Configurations ---
spring.mail.host=mail.example.com
spring.mail.port=587
# spring.mail.username=your-email@gmail.com
# spring.mail.password=your-app-password-or-normal-password # For Gmail, use an App Password!
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
# Optional: Trust all hosts for SSL (useful for local testing, but be cautious in production)
# spring.mail.properties.mail.smtp.ssl.trust=*

# Custom property for the default 'from' address
mail.from-address=noreply@yourdomain.com
