spring.application.name=Driveable

spring.datasource.url=jdbc:mysql://localhost:5432/drivable?useSSL=false
spring.datasource.username=user
spring.datasource.password=password

spring.data.jdbc.dialect=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000

security.jwt.secret-key=YFGzYyrUl99aZTRhn5BDNCaMp3dZrSXL
security.jwt.expiration-time=3600000